from flask import Flask, request, jsonify, render_template
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import json

chatbot = Flask(__name__)

from flask_cors import CORS

CORS(chatbot)

# Predefined answers in a dictionary

predefined_answers = {
    
    "What is the currency in Jamaica?": "The currency in Jamaica is the Jamaican Dollar.",
    "What is the capital of Jamaica?": "The capital of Jamaica is Kingston.",
    "What language is spoken in Jamaica?": "The official language of Jamaica is English, but Jamaican Patois is also widely spoken.",
    "Do I need a visa to visit Jamaica?": "Visa requirements vary depending on your nationality. It is advisable to check the latest visa policies.",
    "Is it safe to travel to Jamaica?": "While Jamaica is generally safe for tourists, it's advisable to follow local advice and take standard precautions.",
    "What is the best time to visit Jamaica?": "The best time to visit Jamaica is from November to mid-December.",
    "What are the must-see attractions in Jamaica?": "Some must-see attractions include Dunn's River Falls, Blue Mountains, and Seven Mile Beach.",
    "What's the driving standard in Jamaica?": "In Jamaica, driving is on the left-hand side of the road.",
    "Can I use my mobile phone in Jamaica?": "Yes, but roaming charges may apply. It's often cheaper to buy a local SIM card.",
    "Is the water safe to drink?": "It's generally safe to drink tap water in Jamaica, but bottled water is recommended for tourists.",
    "What's the food like in Jamaica?": "Jamaican cuisine is diverse, featuring dishes like jerk chicken, ackee and saltfish, and rice and peas.",
    "How do I get around in Jamaica?": "Options for getting around include taxis, buses, and car rentals.",
    "What's the time zone of Jamaica?": "Jamaica is in the Eastern Standard Time Zone (EST), which is UTC -5.",
    "What are the key emergency numbers?": "The general emergency number in Jamaica is 119.",
    "Do I need vaccinations before visiting Jamaica?": "No specific vaccinations are required, but it's advisable to check with health professionals for the most current advice.",
    "What are the popular local dishes?": "Popular local dishes include jerk chicken, oxtail, and ackee and saltfish.",
    "Are credit cards widely accepted?": "Credit cards are widely accepted in most hotels, restaurants, and shops.",
    "What kind of electrical outlets are used?": "Jamaica uses Type A and Type B electrical outlets.",
    "Is tipping customary in Jamaica?": "Tipping is not mandatory but is generally appreciated.",
    "Can I use public transport easily?": "Public transport is available, but may not be as reliable as in some other countries.",
    # General Information
    "What is the currency in Jamaica?": "The currency in Jamaica is the Jamaican Dollar.",
    "What is the capital of Jamaica?": "The capital of Jamaica is Kingston.",
    "What language is spoken in Jamaica?": "The official language of Jamaica is English, but Jamaican Patois is also widely spoken.",
    
    # Travel Logistics
    "Do I need a visa to visit Jamaica?": "Visa requirements vary depending on your nationality. It is advisable to check the latest visa policies.",
    "What's the time zone of Jamaica?": "Jamaica is in the Eastern Standard Time Zone (EST), which is UTC -5.",
    "How do I get around in Jamaica?": "Options for getting around include taxis, buses, and car rentals.",
    "What kind of electrical outlets are used?": "Jamaica uses Type A and Type B electrical outlets.",
    "Is tipping customary in Jamaica?": "Tipping is not mandatory but is generally appreciated.",
    "Can I use public transport easily?": "Public transport is available, but may not be as reliable as in some other countries.",
    
    # Safety and Health
    "Is it safe to travel to Jamaica?": "While Jamaica is generally safe for tourists, it's advisable to follow local advice and take standard precautions.",
    "What are the key emergency numbers?": "The general emergency number in Jamaica is 119.",
    "Do I need vaccinations before visiting Jamaica?": "No specific vaccinations are required, but it's advisable to check with health professionals for the most current advice.",
    "Is the water safe to drink?": "It's generally safe to drink tap water in Jamaica, but bottled water is recommended for tourists.",
    
    # Food and Culture
    "What's the food like in Jamaica?": "Jamaican cuisine is diverse, featuring dishes like jerk chicken, ackee and saltfish, and rice and peas.",
    "What are the popular local dishes?": "Popular local dishes include jerk chicken, oxtail, and ackee and saltfish.",
    "Are credit cards widely accepted?": "Credit cards are widely accepted in most hotels, restaurants, and shops.",
    
    # Attractions and Activities
    "What is the best time to visit Jamaica?": "The best time to visit Jamaica is from November to mid-December.",
    "What are the must-see attractions in Jamaica?": "Some must-see attractions include Dunn's River Falls, Blue Mountains, and Seven Mile Beach.",
    "What's the driving standard in Jamaica?": "In Jamaica, driving is on the left-hand side of the road.",
    
    # Connectivity
    "Can I use my mobile phone in Jamaica?": "Yes, but roaming charges may apply. It's often cheaper to buy a local SIM card.",
    
    # More Questions
    "What are some traditional Jamaican festivals?": "Popular festivals include Reggae Sumfest, Calabash Literary Festival, and Jamaica Carnival.",
    "How do Jamaicans usually greet each other?": "Common greetings include 'Hello', 'Hi', or 'Wah Gwaan' in Patois.",
    "What is the legal drinking age?": "The legal drinking age in Jamaica is 18.",
    "Is smoking allowed in public places?": "Smoking is prohibited in enclosed and specified public places but is generally allowed in open-air locations.",
    "What are the local shopping specialties?": "Local specialties include Blue Mountain Coffee, rum, and handcrafted items.",
    "What wildlife can I expect to see?": "You might encounter various bird species, iguanas, and marine life.",
    "Is Wi-Fi easily accessible?": "Wi-Fi is readily available in most hotels and many restaurants.",
    "Are there any dress code restrictions?": "There are no strict dress codes, but modest attire is recommended for religious and formal settings.",
    "What kind of water activities are available?": "Popular water activities include snorkeling, scuba diving, and kayaking.",
    "Can I go hiking in Jamaica?": "Yes, there are several hiking trails, particularly in the Blue Mountains.",
     # Additional Questions and Answers
    "Is Jamaica LGBTQ+ friendly?": "Public attitudes toward LGBTQ+ issues can vary, and it's advisable to exercise discretion.",
    "What are the national symbols of Jamaica?": "The national symbols include the ackee, the swallowtail hummingbird, and the Blue Mahoe tree.",
    "What are the popular beaches in Jamaica?": "Popular beaches include Negril's Seven Mile Beach, Doctor's Cave Beach, and Frenchman's Cove.",
    "How far is the airport from downtown Kingston?": "Norman Manley International Airport is approximately 19 km from downtown Kingston.",
    "What is Jamaica's national dish?": "The national dish of Jamaica is ackee and saltfish.",
    "Tell me about Jamaican music.": "Jamaica is the birthplace of genres like Reggae and Dancehall. Bob Marley is one of its most famous musicians.",
    "Is English the only language spoken?": "While English is the official language, Jamaican Patois is also widely spoken and understood.",
    "Is Jamaica a part of the British Commonwealth?": "Yes, Jamaica is a member of the Commonwealth of Nations.",
    "What is the approximate population of Jamaica?": "The approximate population is around 3 million people.",
    "Is Jamaica a developed country?": "Jamaica is considered a developing country with a mixed economy.",
    "Can I drive in Jamaica with a U.S. license?": "Yes, you can drive with a valid U.S. license for up to three months.",
    "Do I need travel insurance?": "Travel insurance is highly recommended for any international travel.",
    "What is the political system in Jamaica?": "Jamaica has a parliamentary democracy and is a constitutional monarchy.",
    "How can I get from the airport to my hotel?": "Options include taxis, hotel shuttles, and car rental services.",
    "Is Airbnb available in Jamaica?": "Yes, Airbnb is a popular accommodation option in various parts of Jamaica.",
    "Are there vegetarian-friendly food options?": "Yes, many restaurants offer vegetarian and vegan options.",
    "What kind of wildlife can I see?": "You might encounter various bird species, iguanas, and marine life.",
    "What's the weather like?": "Jamaica has a tropical climate, with hot and humid weather year-round.",
    "Do I need to take malaria tablets?": "Malaria is not common in Jamaica, but consult with healthcare providers for advice.",
    "What kind of shopping can I do?": "You can shop for crafts, rum, coffee, and luxury goods among other items.",
    "What are the public holidays?": "Public holidays include New Year's Day, Labour Day, and Independence Day among others.",
    "What sports are popular in Jamaica?": "Popular sports include cricket, football, and athletics.",
    "Tell me about Jamaican rum.": "Jamaica is known for its high-quality rum, with Appleton Estate being one of the oldest distilleries.",
    "Are there casinos in Jamaica?": "Yes, there are a few casinos and many hotels also offer gaming lounges.",
    "How do I get a local SIM card?": "Local SIM cards can be purchased at the airport or from local providers.",
    "Is there a departure tax?": "A departure tax may be included in your airfare, but it's advisable to check.",
    "What's the nightlife like?": "The nightlife is vibrant, with various bars, clubs, and beach parties to choose from.",
    "Is public transportation safe?": "Public transportation is generally safe but can be crowded. Private taxis are a safer option.",
    "Are U.S. dollars accepted?": "U.S. dollars are widely accepted but expect change in Jamaican dollars.",
    "How do I get to other Caribbean islands from Jamaica?": "There are regional flights and ferries to other Caribbean destinations.",
    "Which countries are the safest?": "Jamaica is generally safe for tourists, especially in resort areas, but it's always best to consult travel advisories for the latest information.",
    "Which countries are the least safe?": "Jamaica has some areas that are advised to be avoided for safety reasons. Always consult the latest travel advisories.",
    "Where can I get travel insurance?": "Travel insurance can be purchased online, through travel agents, or directly from insurance providers.",
    "What type of hotel is this? Is it all-inclusive?": "Jamaica offers a range of hotel options including all-inclusive resorts, boutique hotels, and budget-friendly options.",
    "Does this hotel have free parking?": "Many hotels in Jamaica offer free parking, but it's best to confirm with the specific hotel.",
    "Does this hotel offer airport transfers?": "Many hotels in Jamaica offer airport transfer services, either complimentary or for an additional fee.",
    "Will I get a tour guide?": "Tour guides can often be arranged through your hotel or tour companies in Jamaica.",
    "Which countries can I travel to without a visa?": "Visa requirements depend on your nationality. Citizens of several countries can enter Jamaica without a visa for short stays.",
    "Do I need a visa to go on a connecting flight even if I am not staying in that country?": "Transit visa requirements vary by country. For Jamaica, you generally do not need a transit visa if you won't be leaving the airport.",
    "What are some travel tips you have for this country?": "Always keep an eye on your belongings, stick to well-travelled areas, and sample the local cuisine like jerk chicken.",
    "Is smoking legal in that country?": "Smoking is legal in Jamaica, but there are restrictions in public spaces and within certain distances from public entrances.",
    "Is weed legal in that country?": "Marijuana has been decriminalised in Jamaica for amounts under 2 ounces, and is legal for medical and religious purposes.",
    "Is there a doctor at the hotel?": "Most large resorts in Jamaica have medical facilities and a doctor on call.",
    "How close is the nearest hospital?": "The proximity of the nearest hospital will depend on your location in Jamaica.",
    "What is the vat in this country?": "The standard rate of General Consumption Tax (GCT) in Jamaica is currently 15%.",
    "Which side of the road do they drive?": "In Jamaica, driving is on the left-hand side of the road.",
    "Can I hire a car on the island?": "Yes, you can hire a car in Jamaica from various car rental agencies.",
    "What is the age limit to drive in that country?": "The minimum age to rent a car in Jamaica is generally 23-25, depending on the car rental agency.",
    "What are the activities I can do offsite?": "Popular offsite activities in Jamaica include visiting Dunn's River Falls, snorkelling, and exploring the Blue Mountains.",
    
    # General travel questions
    "How advanced of my trip should I book?": "It's generally advisable to book international trips at least 3-6 months in advance for the best rates and availability.",
    "What are your cancellation policies?": "Cancellation policies vary by service provider. Always check the terms and conditions.",
    "Can I rebook free of charge at any time?": "Rebooking policies are specific to each airline or hotel. Some offer free changes, while others charge fees.",
    "What is the allowed weight for the luggage/suitcase?": "Luggage allowances vary by airline and ticket class. Always check your airline's specific baggage policy.",
    "When is the best time to visit that country?": "The best time to visit Jamaica is from November to mid-December for pleasant weather and less crowd.",
    "What plugs do I need for electronics when visiting that country?": "Jamaica uses Type A and Type B electrical sockets. The standard voltage is 110V.",
    "How do I pay for my trip?": "Payment options typically include credit/debit cards, bank transfers, and sometimes digital wallets like PayPal.",
    "Do you require a deposit?": "Many hotels and tour operators require a deposit to secure your booking.",
    "How do I secure extras on the plane?": "Extras like additional legroom or meals can often be secured during the booking process or by contacting the airline directly.",
    "How early should I get to the airport?": "It's advisable to arrive at least 2-3 hours before a domestic flight and 3-4 hours before an international flight.",
    # Airport Questions
     "What is the check-in process at the airport?": "The check-in process usually involves confirming your booking, selecting seats, and checking in luggage. You can do this at the airline counter or via self-service kiosks.",
    "How early should I arrive at the airport?": "For domestic flights, it's advisable to arrive at least 2 hours in advance. For international flights, aim for at least 3-4 hours.",
    "What documents do I need to present at the airport?": "Generally, you will need a valid passport for international flights and a government-issued ID for domestic flights. Always check specific airline and country requirements.",
    "Is there a fast-track security option?": "Some airports offer fast-track security services for an additional fee or as a perk for premium passengers.",
    "Can I bring liquids in my carry-on?": "Liquids are generally allowed in carry-on luggage in containers of 100 ml or less, and must be placed in a clear, resealable plastic bag.",
    "What is the luggage allowance?": "Luggage allowances vary by airline and ticket class. Always check your airline's specific baggage policy.",
    "How can I find out about flight delays or cancellations?": "Airlines usually send notifications about delays or cancellations. You can also check the airport's website or contact the airline directly.",
    "Is Wi-Fi available at the airport?": "Most major airports offer free Wi-Fi, although the quality and speed can vary.",
    "Are there lounges at the airport?": "Many airports have lounges that can be accessed either through membership, premium tickets, or a one-time fee.",
    "How do I get from the airport to my hotel?": "Transport options usually include taxis, public transport, and sometimes hotel shuttles. Rideshares may also be available.",
    "Is there a currency exchange at the airport?": "Most international airports have currency exchange counters, but rates may not be the most favourable.",
    "What dining options are available at the airport?": "Airports generally offer a variety of dining options, from fast food to sit-down restaurants.",
    "Is duty-free shopping available?": "Duty-free shops are usually available in the international terminals of airports.",
    "What do I do if my luggage is lost or damaged?": "Report lost or damaged luggage to the airline immediately. They will guide you through the process of tracking or compensation.",
    "Can I sleep at the airport?": "While not all airports are equipped for comfortable overnight stays, some do have lounges or rest areas for passengers.",
    "Are pets allowed at the airport?": "Pets are generally allowed but must meet specific airline and airport regulations. Always check in advance.",
    "Is smoking allowed at the airport?": "Most airports have designated smoking areas, although smoking is usually not allowed in terminals.",
    "How do I get around the airport?": "Large airports often offer various forms of internal transportation, such as trams, shuttles, or moving walkways.",
    "Can I request assistance for reduced mobility?": "Airports generally offer assistance for passengers with reduced mobility, but it's best to request this service in advance.",
    "Are there any COVID-19 measures at the airport?": "COVID-19 measures vary by airport but generally include mask mandates, social distancing, and possible testing or quarantine requirements.",
    'What type of hotel is suitable for a family with young children?': "Family-friendly resorts like Beaches Negril Resort & Spa or Franklyn D. Resort & Spa in Runaway Bay offer kids' clubs and activities. For example, Beaches Negril Resort & Spa in Negril, Franklyn D. Resort & Spa in Runaway Bay, or Moon Palace Jamaica in Ocho Rios.",
    'What hotel options are available for couples seeking romance?': "Boutique hotels or resorts with private villas, couple's spa treatments, and intimate dining options are often favoured by couples. For example, Trident Hotel in Portland, GoldenEye in St. Mary, or Geejam in Portland.",
    'Are there budget-friendly hotels for solo travellers?': 'Hostels or guest houses are generally good options for solo travellers. For example, Reggae Hostel in Kingston, Judy House Cottages and Rooms in Negril, or Rasta hostel in Montego Bay.',
    'What hotels are suitable for a short business trip?': 'Hotels located near the business districts, with high-speed Wi-Fi and meeting rooms, are preferable for short business trips. For example, The Jamaica Pegasus Hotel in Kingston, Courtyard by Marriott in Kingston, or Hyatt Ziva Rose Hall in Montego Bay.',
    'Are there any age-restricted hotels?': 'Some adult-only resorts exist, typically catering to guests aged 18 or older. For example, Sandals Royal Caribbean in Montego Bay, Couples Tower Isle in Ocho Rios, or Hedonism II in Negril.',
    'What activities are available for families with young children?': 'Theme parks, zoos, and interactive experiences like Dolphin Cove are generally enjoyable for families with young children. For example, Kool Runnings Water Park in Negril, Hope Zoo in Kingston, or Dolphin Cove in Ocho Rios.',
    'What are some family-friendly beaches?': 'Look for beaches with calm waters, lifeguards, and nearby amenities. For example, Doctor’s Cave Beach in Montego Bay, Seven Mile Beach in Negril, or Puerto Seco Beach in Discovery Bay.',
    'What activities are recommended for couples?': "Romantic activities could include sunset cruises, beachside dinners, or couple's spa days. For example, a sunset cruise in Negril, a beachside dinner at Rick’s Cafe, or a couple’s spa day at Rockhouse Hotel in Negril.",
    'What are some secluded places for couples to visit?': 'Private beaches or waterfalls offer a more intimate setting. For example, Frenchman’s Cove in Portland, Reach Falls in Portland, or Blue Hole in Ocho Rios.',
    'What activities are good for solo travellers?': 'Solo travellers might enjoy hiking, city tours, or cultural activities. For example, hiking in the Blue Mountains, a Kingston city tour, or a visit to the Bob Marley Museum.',
    'Are there any social events or places for solo travellers?': 'Many cities offer group tours or social events. For example, a dancehall night tour in Kingston, a group trip to Dunn’s River Falls, or a cooking class in Montego Bay.',
    'What should I do if I only have a weekend to visit?': 'Focus on must-see landmarks and a handful of activities. For example, a visit to Dunn’s River Falls, a tour of Rose Hall Great House, and a beach day at Montego Bay.',
    'What if I\'m staying for a week or more?': 'A longer itinerary could include day trips to nearby areas. For example, a day trip to Negril for cliff diving, a visit to the Appleton Estate for rum tasting, or multiple days exploring the various beaches.',
    'What type of hotel is suitable for families with teens?': "Resorts with a range of activities like watersports and teen clubs are ideal. For example, Hilton Rose Hall Resort & Spa in Montego Bay, Iberostar Rose Hall Beach in Montego Bay, or Royalton Blue Waters in Falmouth.",
    'Where can one experience authentic Jamaican cuisine?': "Local eateries and jerk centres offer authentic Jamaican cuisine. For example, Scotchies in Montego Bay, Murphy's West End Restaurant in Negril, or Gloria's Rendezvous in Port Royal.",
    'What are some must-visit historical sites?': "Jamaica has a rich history reflected in its landmarks. For example, Port Royal, Rose Hall Great House, or the Bob Marley Museum in Kingston.",
    'What are some nature spots ideal for photography?': "Jamaica offers various picturesque spots. For example, the Blue Hole in Ocho Rios, Blue Lagoon in Portland, or Frenchman's Cove in Portland.",
    'What are the best places for snorkelling?': "Jamaica has several spots known for their marine life. For example, Montego Bay Marine Park, the reefs off Negril, or the Blue Lagoon in Portland.",
    'What spots are recommended for nightlife?': "Various cities in Jamaica offer vibrant nightlife. For example, Margaritaville in Montego Bay, Pier One in Montego Bay, or Jungle Night Club in Negril.",
    'What options are available for luxury shopping?': "For high-end shopping, one could visit places like the Shoppes at Rose Hall in Montego Bay or the Taj Mahal Shopping Center in Ocho Rios.",
    'What cultural festivals are worth attending?': "Jamaica hosts several cultural festivals. For example, the Reggae Sumfest in Montego Bay, Calabash Literary Festival in Treasure Beach, or Carnival in Kingston and Ocho Rios.",
    'What are some good spots for surfing?': "Jamaica has a few spots ideal for surfing. For example, Boston Bay in Portland, Zoo in Bull Bay, or Makka in St. Thomas.",
    'What are popular local drinks one should try?': "Jamaica offers a variety of local drinks. For example, try the local rum at Appleton Estate, Blue Mountain coffee, or Ting, a grapefruit soda.",
    'What options are there for public transport?': "Public transport varies from buses to shared taxis. For example, JUTC buses in Kingston, route taxis in tourist areas, or Knutsford Express for long distances.",
    'What safety tips should tourists keep in mind?': "Common safety advice includes avoiding certain areas at night and being cautious with belongings. For example, avoid walking alone at night in isolated areas, keep an eye on your belongings in crowded places, or use registered taxis.",
    'What are the best months to visit Jamaica?': "The peak season is from December to April, offering great weather but also higher prices. For example, consider visiting during December for festive activities, February for Reggae Month, or April for slightly fewer crowds.",
    'What are some local dishes to try?': "Jamaican cuisine is rich and varied. For example, don't miss out on jerk chicken at Scotchies, ackee and saltfish, or a patty from Juici Patties or Tastee Patties.",
    'Are there any unique fruits to try?': "Jamaica offers a range of tropical fruits. For example, you can try sweetsop, soursop, or the national fruit, ackee.",
    'What are the best places for hiking?': "Jamaica offers several hiking spots with scenic beauty. For example, the Blue Mountains, Reach Falls in Portland, or Cockpit Country.",
    'What options are available for river rafting?': "Jamaica offers some great river rafting experiences. For example, the Martha Brae River in Trelawny, Rio Grande in Portland, or the White River in Ocho Rios.",
    'Where can I find Jamaican crafts and souvenirs?': "Local markets and specialty stores are ideal for this. For example, the Craft Market in Montego Bay, Things Jamaican stores, or Harmony Hall Art Gallery in Ocho Rios.",
    'What are some Jamaican music festivals?': "Jamaica is the home of reggae and offers various music festivals. For example, the Reggae Sumfest in Montego Bay, Rebel Salute in St. Ann, or the Jamaica Jazz & Blues Festival.",
    'What are some adventure sports to try?': "Jamaica offers a variety of adventure sports. For example, ziplining at Chukka Adventure Park, bobsledding at Mystic Mountain, or ATV riding in Sandy Bay.",
    'Are there any famous coffee plantations to visit?': "Jamaica is famous for its Blue Mountain coffee. For example, you can visit the Blue Mountain Coffee Estate, Craighton Estate, or Clifton Mount Estate for a tour.",
    'What are some local rum brands to try?': "Jamaica is known for its quality rum. For example, consider sampling Appleton Estate, Wray & Nephew, or Blackwell Rum.",
    'What are some good spots for bird-watching?': "Jamaica has a diverse range of bird species. For example, the Rocklands Bird Sanctuary in Montego Bay, the Blue Mountains, or the Ecclesdown Road in Portland are good spots.",
    'What are the most popular beaches?': "Jamaica is famous for its beaches. For example, Seven Mile Beach in Negril, Doctor's Cave Beach in Montego Bay, or Frenchman's Cove in Portland are highly recommended.",
    'What are some must-visit historical sites?': "Jamaica is rich in history and culture. For example, consider visiting Port Royal, the former pirate capital; Rose Hall Great House in Montego Bay, known for its legend of the White Witch; or the Bob Marley Museum in Kingston.",
    'Where can I experience authentic Jamaican nightlife?': "For a lively night out, consider places like Margaritaville in Montego Bay, Pier 1, also in Montego Bay, or the Quad in Kingston.",
    'What are some traditional Jamaican festivals?': "Jamaica has several traditional festivals worth attending. For example, the Accompong Maroon Festival celebrates Maroon heritage, while Carnival in Jamaica is a vibrant celebration of music and dance.",
    'Are there any natural hot springs to visit?': "Jamaica has a few natural hot springs known for their therapeutic properties. For example, the Rockfort Mineral Bath in Kingston, Bath Fountain in St. Thomas, or Milk River Bath in Clarendon.",
    'Where can I go for snorkelling and diving?': "Jamaica has several spots perfect for underwater exploration. For example, try the Montego Bay Marine Park, the underwater caves in Negril, or the Port Royal Barrier Reef.",
    'What are some beautiful waterfalls to visit?': "Jamaica is home to some stunning waterfalls. For example, Dunn's River Falls in Ocho Rios, YS Falls in St. Elizabeth, or Reach Falls in Portland.",
    'What are some good places for shopping?': "Jamaica offers various shopping experiences. For example, the Island Village in Ocho Rios, the Shoppes at Rose Hall in Montego Bay, or the Coronation Market in Kingston.",
    'Where can I experience Jamaican reggae music?': "Reggae music is integral to Jamaican culture. For example, you could visit the Trench Town Culture Yard in Kingston, attend a live show at Kingston Dub Club, or experience a beach party in Negril.",
    'What options are there for vegan and vegetarian dining?': "Jamaica offers some good vegan and vegetarian dining options. For example, consider the One Love Vegetarian Cafe in Kingston, Just Natural in Negril, or the vegan options at Scotchies jerk centres.",
    'What are some Jamaican street foods I should try?': "Jamaican street food is a must-try. For example, sample bammy and escovitch fish, jerk chicken from a roadside pan, or a 'sky juice' (shaved ice with syrup).",
    'Where can I see Jamaican art and craft?': "Jamaica has a thriving arts scene. For example, the National Gallery of Jamaica in Kingston, the Harmony Hall Art Gallery in Ocho Rios, or the numerous street artists in tourist areas.",
    'What are some recommended eco-tourism activities?': "Jamaica has several eco-tourism activities. For example, the Ahhh...Ras Natango Gallery and Garden in Camrose, bird-watching tours in the Blue Mountains, or the Black River Safari in St. Elizabeth.",
    'What are some recommended coffee plantations to visit?': "Jamaica is famous for its Blue Mountain coffee. For a coffee experience, you could visit the Clifton Mount Estate in the Blue Mountains, Wallenford Coffee Farm in Kingston, or Old Tavern Coffee Estate in the Blue Mountains.",
    'Where can I go for river rafting?': "River rafting is a popular activity in Jamaica. For example, you could try the Rio Grande in Portland, the Martha Brae River in Trelawny, or the White River in Ocho Rios.",
    'What are some secluded beaches for a quiet day?': "If you're looking for a quieter beach experience, consider Winnifred Beach in Portland, Billy's Bay in Treasure Beach, or Lime Cay off the coast of Kingston.",
    'Where can I go for zip-lining?': "For those interested in zip-lining, Good Hope Estate in Trelawny, Mystic Mountain in Ocho Rios, and YS Falls in St. Elizabeth are popular options.",
    'Where can I find the best jerk chicken?': "Jerk chicken is a Jamaican staple. Some of the best can be found at Scotchies in Montego Bay, Boston Jerk Centre in Portland, or Sweetwood Jerk Joint in Kingston.",
    'What are some popular markets for local produce?': "For a true taste of Jamaica, you could visit Coronation Market in Kingston, Falmouth Market in Trelawny, or Ocho Rios Craft Market in Ocho Rios.",
    'Where can I go for horseback riding?': "Horseback riding is another activity you could consider. For example, Chukka Adventures offers rides in Sandy Bay, Braco Stables in Trelawny, or Half Moon Equestrian Center in Montego Bay.",
    'Where can I learn about Rastafarian culture?': "If you're interested in Rastafarian culture, you could visit the Rastafari Indigenous Village in Montego Bay, the Bobo Ashanti commune in Bull Bay, or the Nyabinghi Centre in Scott's Hall.",
    'What are some places to learn about Jamaican folklore?': "Jamaican folklore is rich and diverse. For example, you could visit the Rose Hall Great House in Montego Bay, famous for the White Witch legend, or the Accompong Maroon Village, known for its warrior history.",
    'Where can I go for deep-sea fishing?': "Deep-sea fishing is a popular activity in Jamaica. For example, you could go fishing in Montego Bay with various charter companies, or try the waters off the coast of Port Antonio.",
     'What are some must-visit historical sites?': "Jamaica is rich in history, so consider visiting Port Royal, once known as the 'Wickedest City on Earth,' or the Seville Great House and Heritage Park in St. Ann, or the Trench Town Culture Yard in Kingston.",
    'Where can I experience authentic reggae music?': "For a true reggae experience, you might want to visit The Bob Marley Museum in Kingston, Alfred’s Ocean Palace in Negril, or attend the annual Reggae Sumfest in Montego Bay.",
    'What are some natural wonders to explore?': "Jamaica offers various natural wonders like the Blue Hole in Ocho Rios, Dunn's River Falls in Ocho Rios, and the Luminous Lagoon in Falmouth.",
    'Where can I try traditional Jamaican food?': "To try traditional Jamaican food, consider visiting Gloria's Rendezvous in Kingston for seafood, Murphy's West End Restaurant in Negril for jerk dishes, or Miss T's Kitchen in Ocho Rios for a variety of local dishes.",
    'Where can I go for snorkeling and scuba diving?': "For underwater activities, popular spots include Montego Bay Marine Park in Montego Bay, the reefs of Negril, or the Blue Lagoon in Port Antonio.",
    'What are some romantic getaways within Jamaica?': "For romantic experiences, consider a stay at The Caves in Negril, GoldenEye in Oracabessa, or Tensing Pen in Negril.",
    'Where can I find luxury shopping?': "For high-end shopping, visit the Shoppes at Rose Hall in Montego Bay or the Taj Mahal Shopping Center in Ocho Rios.",
    'What are the best spots for surfing?': "If you're interested in surfing, Boston Bay in Portland, Long Bay in Portland, and Zoo in Kingston are popular spots.",
    'Where can I enjoy local arts and crafts?': "For local crafts, you might want to visit the Harmony Hall Art Gallery in Ocho Rios, or the Craft Markets in Montego Bay or Kingston.",
    'What spots are good for bird-watching?': "Bird-watching can be enjoyed at various spots like the Blue and John Crow Mountains National Park, Rocklands Bird Sanctuary in Montego Bay, or the Royal Palm Reserve in Negril.",
    'What are some notable museums to visit?': "Jamaica has a range of museums to explore, such as the National Gallery of Jamaica in Kingston, the Outameni Experience in Trelawny, or the Hanover Museum in Lucea.",
    'What are some popular festivals?': "Jamaica is known for its vibrant festivals like Carnival in Kingston, the Accompong Maroon Festival in St. Elizabeth, and the Portland Jerk Festival in Portland.",
    'Where can I experience traditional Jamaican dance?': "For traditional dance, consider attending the Jamaica Dance Umbrella festival in Kingston or performances by the National Dance Theatre Company, also in Kingston.",
    'What are the best places for coffee tasting?': "Jamaica is famous for its Blue Mountain Coffee. You can experience it at the source by visiting the Blue Mountains and touring a coffee estate like the Craighton Estate or Clifton Mount.",
    'Where can I go for horseback riding?': "Horseback riding is available at various locations such as Half Moon Equestrian Center in Montego Bay, Braco Stables in Trelawny, or Chukka Adventures in multiple locations.",
    'What are some good places for hiking and trekking?': "For hiking enthusiasts, the Blue and John Crow Mountains National Park offers various trails. You could also consider Hollywell Recreation Park or the trails leading to the various waterfalls around the island like Mayfield Falls.",
    'Where can I get the best street food?': "For authentic Jamaican street food, consider Faith's Pen along the Ocho Rios to Kingston road, or Hellshire Beach in Portmore for seafood.",
    'What are some local drinks to try?': "Popular local drinks include Ting, a grapefruit soda, Wray and Nephew Overproof Rum, and various natural juices like sorrel and June plum.",
    'Where can I go for deep-sea fishing?': "For deep-sea fishing, you might want to head to Montego Bay, Ocho Rios or Port Antonio, where various operators offer fishing excursions.",
    'What are the best farmers markets or places to get local produce?': "Coronation Market in Kingston is one of the largest in the country, while smaller markets can be found in most towns on specific days of the week.",
    'What can I get for usd 200 USD or £200 or 200 pounds or £1000 or 10000 per night in Jamaica?': "The cost of accommodations in Jamaica can vary based on location, time of year, and the amenities offered. Seasonal pricing does affect the cost, but generally, you can find resorts in the range of 200 to 700 USD per night. For a more luxurious experience with bespoke pricing, consider hotels like Half Moon in Montego Bay, The Cliff Hotel in Negril, or Round Hill Hotel and Villas in Montego Bay.",
    'What type of hotel is suitable for a family with young children?': "Family-friendly resorts like Beaches Negril or the Hilton Rose Hall in Montego Bay offer a variety of activities for children, including water parks and kids' clubs.",
    'What hotel options are available for couples seeking romance?': "For romantic getaways, consider boutique hotels like The Trident Hotel in Portland, GoldenEye in St. Mary, or Geejam also in Portland.",
    'Are there budget-friendly hotels for solo travellers?': "Budget options include guesthouses and smaller hotels like The Knutsford Court Hotel in Kingston or Rooms Ocho Rios in Ocho Rios.",
    'What hotels are suitable for a short business trip?': "For business trips, the Pegasus Hotel and the Spanish Court Hotel in Kingston offer convenient locations and business amenities.",
    'What can I get for $200 per night?': "Seasonal pricing may affect rates, but mid-range resorts like Jewel Dunn's River in Ocho Rios generally fall within this budget. For more bespoke experiences, hotels like Round Hill Hotel will require a higher budget.",
    'What activities are available for families with young children?': "Families often enjoy Kool Runnings Water Park in Negril, Mystic Mountain in Ocho Rios, or Dolphin Cove, also in Ocho Rios.",
    'What are some family-friendly beaches?': "Doctor's Cave Beach in Montego Bay, Seven Mile Beach in Negril, and Treasure Beach in St. Elizabeth are known for their family-friendly atmosphere.",
    'What activities are recommended for couples?': "Couples may enjoy a bamboo raft trip down the Martha Brae River, a visit to the Luminous Lagoon, or a romantic dinner at the cliffside restaurant, Pushcart, in Negril.",
    'What are some secluded places for couples to visit?': "Frenchman's Cove in Portland, Lime Cay off the coast of Kingston, or Tensing Pen in Negril offer more secluded options.",
    'What activities are good for solo travellers?': "Solo travellers might enjoy a hike up the Blue Mountains, a visit to the Bob Marley Museum in Kingston, or surfing lessons at Boston Bay Beach.",
    'Are there any social events or places for solo travellers?': "Kingston's Dub Club, Rick's Café in Negril, or various 'fish fry' events offer social atmospheres suitable for solo travellers.",
    'What should I do if I only have a weekend to visit?': "With limited time, focus on closer attractions like Dunn's River Falls and the Blue Hole if you're in Ocho Rios, or the Hip Strip if you're in Montego Bay.",
    "What if I'm staying for a week or more?": "With more time, consider exploring multiple parishes, such as a few days in Negril for beach activities and another few in Portland for a more laid-back, natural setting.",
    'What are some notable museums to visit?': "Consider the National Gallery of Jamaica in Kingston, the Outameni Experience in Trelawny, or the Hanover Museum in Lucea.",
    'What are some popular festivals?': "Carnival in Kingston, the Accompong Maroon Festival in St. Elizabeth, and the Portland Jerk Festival are vibrant cultural experiences.",
    'Where can I experience traditional Jamaican dance?': "The Jamaica Dance Umbrella festival in Kingston or performances by the National Dance Theatre Company offer traditional dance experiences.",
    'What are the best places for coffee tasting?': "Visit the Blue Mountains and tour coffee estates like the Craighton Estate or Clifton Mount for authentic Jamaican coffee.",
    'Where can I go for horseback riding?': "Options include Half Moon Equestrian Center in Montego Bay, Braco Stables in Trelawny, or Chukka Adventures in various locations.",
    'What are some good places for hiking and trekking?': "The Blue and John Crow Mountains National Park and Hollywell Recreation Park offer various trails.",
    'Where can I get the best street food?': "Faith's Pen along the Ocho Rios to Kingston road, or Hellshire Beach in Portmore are popular for street food.",
    'What are some local drinks to try?': "Try Ting, a grapefruit soda, Wray and Nephew Overproof Rum, or natural juices like sorrel.",
    'Where can I go for deep-sea fishing?': "Montego Bay, Ocho Rios or Port Antonio offer various operators for fishing excursions.",
    'What are the best farmers markets or places to get local produce?': "Coronation Market in Kingston is the largest, while smaller markets can be found in most towns.", 
    'What are some good spots for snorkelling and diving?': "The Montego Bay Marine Park offers various snorkelling spots, while Runaway Bay and Port Antonio provide excellent scuba diving opportunities. Notable dive spots include Devil's Reef and the Kathryn Wreck.",
    'How can I experience Jamaican music live?': "For live music, consider visiting Kingston Dub Club for reggae, or Jazz & Blues bars in Montego Bay. Events like Reggae Sumfest offer a festival atmosphere.",
    'Where can I find authentic Jamaican crafts?': "Craft markets in Ocho Rios, Negril, and Montego Bay offer a variety of handmade goods. The Harmony Hall Art Gallery in Ocho Rios showcases local artisans.",
    'What are some recommended plantation tours?': "The Good Hope Estate near Falmouth offers a comprehensive plantation tour, including a Great House visit. Appleton Estate in St. Elizabeth allows you to delve into rum-making.",
    'How do I use public transportation?': "Public buses operate in major towns and cities. Route taxis are common for shorter distances. Always confirm the fare before starting your journey.",
    'What are some unusual or unique attractions?': "The Luminous Lagoon in Falmouth offers a chance to see natural bioluminescence, while the Rastafari Indigenous Village near Montego Bay provides cultural insights.",
    'Where can I go ziplining?': "Chukka Caribbean Adventures offers ziplining in multiple locations, including Montego Bay and Ocho Rios. Yaaman Adventure Park in Ocho Rios also has a zipline course.",
    'Is it safe to travel outside of the resort areas?': "While many tourists stay in resort areas for safety, it's possible to explore outside safely. Always take local advice, use reputable transportation, and exercise caution.",
    'What local dishes should I try?': "Don't leave without trying jerk chicken or pork, ackee and saltfish, or a traditional Jamaican patty. Devon House in Kingston offers some of the best ice cream.",
    'How do I get a local SIM card for my phone?': "Local SIM cards can be purchased from providers like Digicel or Flow, available at the airport and various other locations.",
    'Where can I find adult-only resorts?': "Sandals Resorts offer adult-only options in Montego Bay and Ocho Rios. The Caves in Negril is another adult-only accommodation.",
    'What are the rules and norms around tipping?': "Tipping is generally appreciated but not obligatory. A 10-15% tip is standard in restaurants. Some all-inclusive resorts include gratuities in the bill.",
    'What are the peak tourist seasons in Jamaica?': "Peak seasons in Jamaica generally coincide with the winter months of December to April. This is when the weather is most favourable, but prices for flights and accommodations may be higher.",
    'What are the main international airports?': "Jamaica has three main international airports: Sangster International Airport in Montego Bay, Norman Manley International Airport in Kingston, and Ian Fleming International Airport in Ocho Rios.",
    'What are the visa requirements for travellers?': "Visa requirements vary by nationality. Many countries, such as the United States, Canada, and the UK, do not require a visa for stays up to 90 days.",
    'Is travel insurance required?': "Travel insurance is not mandatory but is highly recommended for medical emergencies, trip cancellations, or other unexpected events.",
    'What are the options for internal travel?': "Internal travel can be done by domestic flights, buses, or taxis. Car rentals are also available but remember that driving is on the left side of the road in Jamaica.",
    'What vaccinations are recommended?': "Routine vaccines like MMR, diphtheria-tetanus-pertussis, and polio are generally recommended. Hepatitis A and Typhoid vaccines are also advised for most travellers.",
    'What is the currency and where can it be exchanged?': "The Jamaican Dollar (JMD) is the local currency. It can be exchanged at banks, hotels, or licensed exchange bureaus.",
    'What languages are spoken?': "The official language is English, but many locals also speak Patois, a Jamaican Creole language.",
    'What is the electrical outlet standard?': "Jamaica uses Type A and Type B plugs, similar to the United States, with a standard voltage of 110V.",
    'Are there any cultural norms or etiquettes tourists should be aware of?': "Respect for local customs and traditions is appreciated. Casual beach attire is fine for resorts but less appropriate in cities or religious settings.",
    'What are the emergency contact numbers?': "The general emergency number for police, fire, and ambulance services is 119.",
    'Is there a tourism board or official tourist information centres?': "Yes, the Jamaica Tourist Board provides information and has offices in both Montego Bay and Kingston.",
     'What are some traditional Jamaican dishes to try?': "Jamaican cuisine offers a variety of dishes, including Jerk chicken, Ackee and Saltfish, and Patties. Popular eateries to try these include Scotchies in Montego Bay or Juici Patties found island-wide.",
    'Are there any local customs or festivals that tourists can participate in?': "Visitors can take part in festivals like Reggae Sumfest in Montego Bay or Rebel Salute in Priory, St. Ann. Emancipation and Independence Days in early August are also widely celebrated.",
    'What are the public transport options?': "Public transport includes buses, minibuses, and route taxis. The JUTC operates in the Kingston Metropolitan area, and Knutsford Express provides long-distance services between major cities.",
    'What water activities are available?': "Jamaica offers a wide range of water activities such as snorkelling, scuba diving, and sailing. Popular locations include Montego Bay Marine Park and Dolphin Cove in Ocho Rios.",
    'How safe is it for tourists?': "Tourist areas are generally safe, but it's advisable to take standard precautions. Some areas, particularly in Kingston, are best avoided, especially at night.",
    'What are some unique souvenirs to bring back?': "Blue Mountain Coffee, Appleton Estate Rum, and handcrafted items like straw hats or wooden sculptures make unique souvenirs. The Craft Market in Montego Bay or Kingston is a good place to shop.",
    'What are some recommended day trips?': "Popular day trips include a visit to the Dunn's River Falls in Ocho Rios, Negril's Seven Mile Beach, or the Bob Marley Museum in Kingston.",
    'Are there any UNESCO World Heritage Sites?': "The Blue and John Crow Mountains were designated a UNESCO World Heritage Site in 2015. They offer rich biodiversity and cultural heritage.",
    'What are the options for eco-friendly travel?': "Eco-tourism is growing in Jamaica with options like the Ambassabeth Cabins in the Blue Mountains or the Rhodes Eco-Resort in Port Antonio.",
    'What kind of wildlife can be observed?': "Birdwatchers can spot over 300 species of birds, including the national bird, the Doctor Bird. Marine life like dolphins and turtles can be observed in marine parks or during specific tours.",
    'What types of accommodations are available?': "Jamaica offers a range of accommodations from luxury resorts to budget hostels. For a unique experience, consider staying at The Caves in Negril or Jakes Hotel in Treasure Beach.",
    'What are some must-visit historical sites?': "Rose Hall Great House in Montego Bay, Fort Charles in Port Royal, and the Seville Great House in St. Ann are important historical sites worth visiting.",
    'Where can I find information on hiking trails?': "The Blue and John Crow Mountains National Park offers various trails for hiking enthusiasts. You can find more information on their official website [Jamaica's National Parks](https://www.nepa.gov.jm/new/services_products/parks_reserves/) or on hiking guides like [AllTrails](https://www.alltrails.com/jamaica).",
    'What are some reputable tour companies for adventure activities?': "Companies like Chukka Adventures and Island Routes offer various adventure tours. You can visit their websites [Chukka](https://chukka.com/) or [Island Routes](https://www.islandroutes.com/) for more details.",
    'Where can I learn about Jamaican music and culture?': "The Bob Marley Museum in Kingston and the Peter Tosh Museum are great places to start. More information can be found on their websites [Bob Marley Museum](http://www.bobmarleymuseum.com/) and [Peter Tosh Museum](https://petertosh.com/museum/).",
    'What are some local art galleries to visit?': "The National Gallery of Jamaica in Kingston is a must-visit. You can also consider galleries like Harmony Hall in Ocho Rios. Websites: [National Gallery](https://natgalja.org.jm/) and [Harmony Hall](http://www.harmonyhall.com/).",
    'Where can I take cooking classes to learn Jamaican cuisine?': "Places like the Gastronomy Centre in Kingston offer cooking classes. Check out their website [Jamaica Cultural Enterprises](https://www.jamaicaculinarytours.com/) for more information.",
    'What are some golf courses for enthusiasts?': "Jamaica has several golf courses like the Tryall Club and White Witch Golf Course. More details can be found on their websites [Tryall Club](https://tryallclub.com/) and [White Witch](https://www.whitewitchgolf.com/).",
    'Where can I go for wellness retreats?': "Wellness retreats are available at places like the GoldenEye Hotel and the Rockhouse Hotel. Websites: [GoldenEye](https://www.goldeneye.com/) and [Rockhouse](https://www.rockhouse.com/).",
    'What are the options for scuba diving?': "Dive sites are abundant in places like Montego Bay and Negril. Companies like Dressel Divers and Resort Divers offer packages. Websites: [Dressel Divers](https://www.dresseldivers.com/diving/jamaica-diving/) and [Resort Divers](http://www.resortdivers.com/).",
    'Where can I find the best luxury shopping?': "For luxury shopping, you may want to visit the Shoppes at Rose Hall in Montego Bay. Website: [The Shoppes at Rose Hall](http://theshoppesatrosehall.com/).",
    'Where can I find information about bird watching tours?': "Birdwatching tours can be arranged through companies like Jamaica Birding. More information can be found on their website [Jamaica Birding](https://www.jamaicabirding.com/).",
    'Where can I find the best reggae music experiences?': "For a rich reggae experience, visit the Bob Marley Museum in Kingston, or the annual Reggae Sumfest in Montego Bay. More information can be found on [bobmarleymuseum.com](https://www.bobmarleymuseum.com/) and [reggaesumfest.com](https://reggaesumfest.com/).",
    'What are some good cooking classes to understand Jamaican cuisine?': "Cooking classes can offer a deep dive into Jamaican cuisine. Websites like [Cook Like a Jamaican](https://cooklikeajamaican.com/) or [Airbnb Experiences](https://www.airbnb.com/experiences) often list such classes.",
    'Where can I find information about birdwatching?': "Jamaica offers a range of birdwatching experiences, particularly in the Cockpit Country and the Blue Mountains. Websites like [birdlifejamaica.org](http://www.birdlifejamaica.org/) and [jamaicabirding.com](http://www.jamaicabirding.com/) could be useful.",
    'Where can I learn about the history of Jamaica?': "For those interested in history, the National Museum Jamaica and the Seville Great House offer fascinating insights. More information can be found on [instituteofjamaica.org.jm](http://instituteofjamaica.org.jm/) and [jnht.com](http://www.jnht.com/).",
    'What are some of the best diving spots?': "Jamaica offers excellent diving spots in areas like Runaway Bay and Port Royal. Websites like [PADI](https://www.padi.com/) can provide certified dive shop listings.",
    'Where can I find wellness or yoga retreats?': "For wellness retreats, consider destinations like Negril or the Blue Mountains. Websites like [BookYogaRetreats](https://www.bookyogaretreats.com/) often list available options in Jamaica.",
    'Where can I find information about local fishing tournaments?': "Fishing tournaments are common in areas like Montego Bay. Websites like [jamaicasportsfishing.com](http://www.jamaicasportsfishing.com/) could provide more details.",
    'Where can I find information on hiking tours?': "For hiking tours, consider companies that specialize in eco-tourism. Websites like [Island Routes](https://www.islandroutes.com/) may have what you're looking for.",
    'What are some renowned art galleries?': "Galleries like the National Gallery of Jamaica offer a look into the island's artistic culture. Visit their website at [nationalgalleryofjamaica.wordpress.com](https://nationalgalleryofjamaica.wordpress.com/).",
    'Where can I find luxury shopping?': "For luxury shopping, visit areas like the Shoppes at Rose Hall in Montego Bay. More information can be found at [theshoppesatrosehall.com](http://www.theshoppesatrosehall.com/).",
    'What are the best places to stay in Kingston?': "In Kingston, you might consider The Spanish Court Hotel for its modern amenities, The Jamaica Pegasus for its business facilities, or Strawberry Hill for a more secluded mountain experience.",
    'Where should I stay in Montego Bay?': "Montego Bay offers a range of options, such as Half Moon Resort for luxury, Secrets St. James for adults-only, and Holiday Inn Resort for a family-friendly atmosphere.",
    'What are some good hotels in Ocho Rios?': "In Ocho Rios, consider staying at Sandals Ochi for an all-inclusive experience, Jamaica Inn for a more boutique feel, or Beaches Ocho Rios for a family vacation.",
    'Where can I find the best accommodations in Negril?': "Negril is known for its beach resorts like The Caves, which offers cliffside cottages, Azul Beach Resort for an all-inclusive stay, and Hedonism II for an adults-only experience.",
    'What are the top places to stay in Port Antonio?': "In Port Antonio, consider Geejam for its private setting, Trident Hotel for luxury, or Hotel Mockingbird Hill for an eco-friendly option.",
    'Best places to stay in Trelawny?': "Trelawny offers options like Excellence Oyster Bay for an adult-only experience, Royalton Blue Waters for families, and Glistening Waters for something unique.",
    'Can you recommend places to stay in St. Elizabeth?': "In St. Elizabeth, Jakes Hotel offers a bohemian atmosphere, while Lashings Boutique Hotel provides a more modern setting, and Button Beach Getaway is great for budget-conscious travellers.",
    'Best accommodations in each major parish?': "For Kingston, consider The Spanish Court Hotel; in Montego Bay, Half Moon Resort is a top pick; Ocho Rios offers Jamaica Inn; Negril has The Caves; Port Antonio is known for Geejam; Trelawny features Excellence Oyster Bay; and St. Elizabeth offers Jakes Hotel.",
     'What are some popular wedding venues in Jamaica?': "Popular wedding venues include Rose Hall Great House in Montego Bay, Doctor's Cave Beach in St. James, and The Tryall Club in Hanover. For a full list, visit [our website](#).",
    'Can you recommend a wedding planner?': "We recommend XYZ Planners, who specialise in destination weddings in Jamaica. For more details, check out their [website](#).",
    'What is the best time of year to get married in Jamaica?': "The best time to get married in Jamaica ranges from November to mid-December. For more details on weather and availability, click [here](#).",
    'What are romantic activities for honeymooners in Jamaica?': "Consider options like sunset cruises, couples massages at beachfront resorts, and private dinners. Detailed suggestions are available [here](#).",
    'Can you suggest some honeymoon packages?': "We offer a variety of packages, ranging from all-inclusive resorts to excursions and romantic dinners. Check out our [honeymoon packages](#).",
    'Are there any adults-only resorts perfect for honeymoons?': "Yes, resorts like Sandals and Couples are adult-only and ideal for honeymooners. More information can be found [here](#).",
     'Any tips for newlyweds travelling to Jamaica for the first time?': "Being aware of local customs, knowing some basic phrases, and ensuring vaccinations are up to date are good tips. Visit [our travel guide](#) for more.",
    'Are there any special deals for newlyweds?': "Many resorts offer newlywed discounts, special packages, romantic dinners, room upgrades, and complimentary spa treatments. See [our special deals page](#).",
    'Can newlyweds get a local SIM card easily?': "Yes, local SIM cards are easily available at the airport or local shops. A detailed [guide](#) is available for more information.",
    'Where are the best places to have a beach wedding in Jamaica?': "Beach weddings are popular in Negril, Montego Bay, and Ocho Rios. Specific locations include Seven Mile Beach in Negril, Doctor's Cave Beach in Montego Bay, or Dunn's River Falls in Ocho Rios.",
    'What are some all-inclusive resorts that offer wedding packages?': "Sandals Resorts, Secrets Resorts, and Iberostar Hotels & Resorts all offer comprehensive wedding packages that include ceremony, reception, and honeymoon amenities.",
    'Are there any wedding planners specializing in destination weddings in Jamaica?': "Yes, companies like Tropical Weddings Jamaica and Helen G Events are known for planning destination weddings.",
    'What are the legal requirements for getting married in Jamaica?': "Generally, you'll need a marriage license from the Ministry of Justice in Jamaica. Requirements include proof of citizenship, proof of marital status, and parental consent if under 18.",
    'What are some unique wedding venues in Jamaica?': "For something different, consider Rose Hall Great House in Montego Bay, the Strawberry Hill in the Blue Mountains, or the Trident Castle in Port Antonio.",
    'Can you recommend floral designers for weddings in Jamaica?': "Tai Flora Luxe and Petals and Promises are well-known floral designers specializing in wedding arrangements.",
    'Where can I find a photographer for my wedding?': "Companies like Saab Weddings and Dwayne Watkins Photography are highly rated and specialize in weddings.",
    'What are the best months for a wedding in Jamaica?': "The peak wedding season in Jamaica is from January to March, due to the pleasant weather. However, you can find good deals in the off-season months like May and November.",
    'Where can I have my wedding?': "Jamaica offers a plethora of venues for weddings, from luxurious resorts to secluded beaches. Popular destinations include Montego Bay, Ocho Rios, and Negril. Specific venues might include Rose Hall Great House in Montego Bay, the Trident Castle in Port Antonio, or Seven Mile Beach in Negril.",
    'Which resort is best for weddings?': "The 'best' resort for weddings can depend on your specific needs, but some resorts are particularly popular for weddings due to their comprehensive packages and beautiful locations. Sandals Resorts, Secrets Resorts, and Iberostar Hotels & Resorts are among those that offer all-inclusive wedding packages in picturesque settings."
}



# Create a TF-IDF Vectorizer
vectorizer = TfidfVectorizer()

# Fit the vectorizer to the questions
vectorizer.fit(predefined_answers.keys())

@chatbot.route('/', methods=['GET'])
def home():
    return render_template('chatbot1.html')


@chatbot.route('/ask', methods=['POST'])
def ask():
    query = request.json.get('query')
    query_vector = vectorizer.transform([query])

    predefined_vectors = vectorizer.transform(predefined_answers.keys())
    similarity_scores = cosine_similarity(query_vector, predefined_vectors)
    max_index = np.argmax(similarity_scores)

    most_similar_question = list(predefined_answers.keys())[max_index]
    answer = predefined_answers[most_similar_question]

    return jsonify({"answer": answer})

#if __name__ == '__main__':
    #chatbot.run(debug=True)
if __name__ == '__main__':
    port = int(os.environ.get("PORT", 5000))
    app.run(host='0.0.0.0', port=port)






